#!/usr/bin/env bash
echo "== create bucket"
if [ -z "$1" ];then
    echo "Cần có tên"
    exit 1
fi

bucket_name=$1 

aws s3api create-bucket \
--bucket "$bucket_name" \
--create-bucket-configuration "LocationConstraint=ap-southeast-1" \
--query Location \
--output text
