#!/usr/bin/env bash

echo "== Deploying CloudFormation Stack for s3 bucket via CFN =="

aws cloudformation deploy \
  --stack-name my-testing-stack \
  --template-file template.yaml \
  -- no-execute-changeset \
  --region ap-southeast-1 \